### PR TITLE
Encoding issues fix refactor

### LINKED ISSUE #51: Report invalid UTF-8 sequence in input mnemonic as `EX_DATAERR = 65`
~~~
'utf-8' codec can't decode byte 0xca in position 151: invalid continuation byte
'utf-8' codec can't decode byte 0xa5 in   position 85: invalid start byte
'utf-8' codec can't decode byte 0x96 in   position 89: invalid start byte
'utf-8' codec can't decode byte 0xc2 in   position 39: invalid continuation byte
'utf-8' codec can't decode byte 0xdb in   position 111: invalid continuation byte
'utf-8' codec can't decode byte 0xc6 in   position 352: invalid continuation byte
'utf-8' codec can't decode byte 0xf3 in   position 56: invalid continuation byte
'utf-8' codec can't decode byte 0xc0 in   position 58: invalid start byte
'utf-8' codec can't decode byte 0xd0 in   position 56: invalid continuation byte
'utf-8' codec can't decode byte 0x84 in   position 123: invalid start byte
'utf-8' codec can't decode byte 0xb5 in   position 140: invalid start byte
'utf-8' codec can't decode byte 0xfe in   position 138: invalid start byte
'utf-8' codec can't decode byte 0x88 in   position 237: invalid start byte
'utf-8' codec can't decode byte 0xc0 in   position 175: invalid start byte
'utf-8' codec can't decode byte 0xfb in   position 132: invalid start byte
'utf-8' codec can't decode byte 0xed in   position 71: invalid continuation byte
'utf-8' codec can't decode byte 0xf7 in   position 53: invalid start byte
'utf-8' codec can't decode byte 0xfe in   position 197: invalid start byte
'utf-8' codec can't decode bytes in   position 2-4: invalid continuation byte
'utf-8' codec can't decode byte 0xbe in   position 66: invalid start byte
'utf-8' codec can't decode byte 0xe4 in   position 7: invalid continuation byte
~~~
Is currently reported as `UNKNOWN_FAILURE = 1`. Would be better to report it as `EX_DATAERR = 65` from `mnemoniccli.ExitCode.EX_DATAERR`.

Already mentioned in https://github.com/mvondracek/PA193_mnemonic_Slytherin/issues/12#issuecomment-543391802.

Errors with UTF-8 apply to dictionary, too. (https://github.com/mvondracek/PA193_mnemonic_Slytherin/pull/21#discussion_r336257567)

### LINKED ISSUE #52: Report invalid hexastring in input seed or entropy as `EX_DATAERR = 65`
~~~
string argument   should contain only ASCII characters
Odd-length string
Non-hexadecimal digit found
~~~

Is currently reported as `UNKNOWN_FAILURE = 1`. Would be better to report it as `EX_DATAERR = 65` from `mnemoniccli.ExitCode.EX_DATAERR`.

### PR DESCRIPTION
**Pull request by mvondracek**
Closes #51
Closes #52

### CODE REVIEW

**Comment by mvondracek** [comment]
Fixed. Tests are passing on Travis and on my computer. 
@sobuch, can you please run fuzzing? And @lsolodkova, can you please test on your computer where you had error with different default encoding? It should be good now.

**Comment by mvondracek** [comment]
See #65

**Comment by mvondracek** [comment]
Closes #51
Closes #52

**Review by lsolodkova — APPROVED** [review]
For me all is OK now, thanks!

**Comment by sobuch** [comment]
fuzzing since morning, nothing relevant

**Comment by mvondracek** [comment]
Great news! ;) I’m away from computer now, so I’ll be glad if you’ll let it fuzz on your PC for a while. :D 

--
Martin Vondráček

31. 10. 2019 v 10:19, sobuch <notifications@github.com>:

**Pull request merged**
