### PR TITLE
Function stubs for basic functionality

### PR DESCRIPTION
**Pull request by mvondracek**
Public API is only `generate`, `recover`, `verify`.

### CODE REVIEW

**Review by lsolodkova — APPROVED** [review]

**Review by sobuch — COMMENTED** [review]
as per https://is.muni.cz/auth/el/fi/podzim2019/PA193/um/PA193_Projects_2019.pdf pages 4-5: shouldnt we use hexa strings as output instead of bytes? For input it also seems we should accept both versions. (can be done, see https://stackoverflow.com/questions/33945261/how-to-specify-multiple-return-types-using-type-hints). Inputs of private functions should then be unified to one of these, for my part it doesnt matter which, so I suppose the one which is easier to convert to.

**Comment by mvondracek** [comment]
I think that a way how CLI tool communicates with user and internal handling of data are two separate things. Our CLI tool should accept binary or hexa strings. However, I suggest that our package handles seed and entrophy as single type. Whether it should be `bytes` or `str` depends on operations we will perform with seed and entropy. What do you think?

**Comment by sobuch** [comment]
Ok, you are right that its different, but, if  we are implementing checks for both formats of input we may as well include both in the library. Or would that make the interface messy? Based on the required functionality seed should be definitely a string, entropy would make more sense to me as bytes, but I am not sure here.

**Comment by lsolodkova** [comment]
> seed should be definitely a string

Why should it? Should we display it or store somewhere? Actually, it's used for generating wallets, but the functionality of our project ends at this point.

**Comment by sobuch** [comment]
page 5 specifies "Output: seed and initial entropy as hexadecimal strings"

**Comment by mvondracek** [comment]
As seed is output from PBKDF2, it could be more efective to handle it as `bytes`. 
I am talking about separation of real data and representation of that data. Our tool should now read seed and entropy as hexa or binary and then print them as hexa strings. 

What about having seed and entropy as bytes for now? It can be changed, if implementation proves that string would be better.

**Comment by sobuch** [comment]
Ok

**Review by sobuch — APPROVED** [review]

**Comment by lsolodkova** [comment]
I bet it wouldn't, but anyway we could add some functionality for converting input from string to bytes.

**Comment by mvondracek** [comment]
Input conversion is a one-liner. I'll do that in CLI tool.

**Pull request merged**
